export const VISA_SERVICE_CATEGORIES = ['Visa - Cambodia', 'Visa - Foreigner'] as const;

export type VisaServiceCategory = typeof VISA_SERVICE_CATEGORIES[number];

export const VISA_SERVICES: Record<VisaServiceCategory, readonly string[]> = {
 'Visa - Foreigner': [
  'VISAX-KH | EB | SIN-1M-1M | S | FOR (Unrestricted)',
  'VISAX-KH | EB | SIN-3M-3M | S | FOR (Unrestricted)',
  'VISAX-KH | EB | MUL-6M-6M | S | FOR (Unrestricted)',
  'VISAX-KH | EB | MUL-12M-12M | S | FOR (Unrestricted)',
  'VISAX-KH | EB | EXPRESS | NA | FOR (Unrestricted)',
  'VISAX-KH | EB | SIN-1M-1M | S | FOR (Restricted)',
  'VISAX-KH | EB | SIN-3M-3M | S | FOR (Restricted)',
  'VISAX-KH | EB | MUL-6M-6M | S | FOR (Restricted)',
  'VISAX-KH | EB | MUL-12M-12M | S | FOR (Restricted)',
  'WP | EB | 1 Year | FOR (Unrestricted)',
  'WP | EB | 1 Year | FOR (Restricted)',
  'WP | EP | Penalty',
  'VISA-KH | TOU (T) | SIN-V90D-30D | E | FOR',
  'VISA-KH | BUS (E) | SIN-V90D-30D | E | FOR',
  'VISA-JP | TOU | SIN-V90D-15D | E | FOR',
  'VISA-JP | TOU | SIN-V90D-15D | S | FOR',
  'VISA-JP | TOU | MUL-DIS-15D | S | FOR',
  'VISA-KR | TOU | SIN-V90D-DIS | E | FOR',
  'VISA-HK | TOU | SIN-V90D-DIS | E | FOR',
  'VISA-HK | TOU | DOU-V90D-DIS | E | FOR',
  'VISA-HK | TOU | EXPRESS | NA | FOR',
  'VISA-VN | TOU | SIN-V90D-90D | E | FOR',
  'VISA-VN | TOU | MUL-V90D-90D | E | FOR',
  'VISA-VN | TOU | SIN-DIS-DIS | S | FOR',
  'VISA-VN | TOU | MUL-DIS-DIS | S | FOR',
  'VISA-VN | TOU | EXPRESS | NA | FOR',
  'VISA-TH | TOU | SIN-V90D-60D | E | FOR',
  'VISA-TH | TOU | MUL-V180D-60D | S | FOR',
  'VISA-AU | TOU(TS) | DIS-DIS-DIS | E | FOR',
  'VISA-AU | TOU | BIOMETRIC',
  'VISA-MY | TOU | SIN-V180D-DIS | E | FOR',
  'VISA-MY | TOU | MUL-V180D-DIS | E | FOR',
  'VISA-US | TOU | DIS-DIS-DIS | S | FOR',
  'VISA-CA | TOU | DIS-DIS-DIS | S | FOR',
  'VISA - CA | TOU | BIOMETRIC',
  'VISA-UK | TOU | DIS - DIS - DIS | E | FOR',
  'VISA-UK | TOU | MUL - V2Y - 6M | E | FOR',
  'VISA-UK | TOU | MUL - V5Y - 6M | E | FOR',
  'VISA-UK | TOU | MUL - V10Y - 6M | E | FOR',
  'VISA - UK | TOU | BIOMETRIC',
  'VISA - EU | SVS(C) | DIS - DIS - DIS | S | FOR',
  'VISA - EU | SVS(C) | BIOMETRIC',
  'VISA-CN | TOU | SIN-V90D-30D | S | FOR',
  'VISA-CN | TOU | DOU-V180D-30D | S | FOR',
  'VISA-CN | TOU | MUL-V365D-30D | S | FOR',
  'VISA-CN | BUS | SIN-V90D-30D | S | FOR',
  'VISA-CN | BUS | DOU-V180D-30D | S | FOR',
  'VISA-CN | BUS | MUL-V365D-DIS | S | FOR',
  'VISA-CN | NBS | DIS-DIS-DIS | S | FOR',
  'VISA-CN | STU (X1) | SIN-V90-NA | S | FOR',
  'VISA-CN | STU (X2) | SIN-DIS-180D | S | FOR',
  'VISA-CN | FAM (Q1) | SIN-V90D-DIS | S | FOR',
  'VISA-CN | FAM (Q2) | SIN-V90D-30D | S | FOR',
  'VISA-CN | FAM (Q2) | DOU-V180D-DIS | S | FOR',
  'VISA-CN | FAM (Q2) | MUL-V365D-DIS | S | FOR',
  'VISA-CN | FAM (S1) | SIN-V90D-NA | S | FOR',
  'VISA-CN | FAM (S2) | SIN-V90D-180D | S | FOR',
  'VISA-CN | FAM (S2) | DOU-V180D-DIS | S | FOR',
  'VISA-CN | FAM (S2) | MUL-V365D-DIS | S | FOR',
  'VISA-ID | TOU | SIN-V90D-30D | E | FOR',
  'VISA-IN | TOU | DOU-DIS-30D | E | FOR',
  'VISA-MM | TOU | SIN-V90D-DIS | E | FOR',
  'VISA-MM | TOU | DIS-DIS-28D | S | FOR',
  'VISA-TR | TOU | SIN-DIS-DIS | S | FOR',
  'VISA-PH | TOU | SIN-V90D-DIS | E | FOR',
  'VISA - RU | TOU | SIN-DIS-DIS | S | FOR',
  'VISA-AE | TOU | SIN-V60D-30D | E | FOR',
  'VISA-NZ | TOU | DIS-DIS-DIS | E | FOR',
  'VISA-PK | TOU | SIN-V90D-30D | E | FOR',
 ],
 'Visa - Cambodia': [
  'VISA-CN | ALL | EXPRESS | NA | KHM & FOR',
  'VISA-CN | TOU | SIN-V90D-30D | S | KHM',
  'VISA-CN | TOU | DOU-V180D-30D | S | KHM',
  'VISA-CN | TOU | MUL-V365D-30D | S | KHM',
  'VISA-CN | BUS | SIN-V90D-30D | S | KHM',
  'VISA-CN | BUS | DOU-V180D-30D | S | KHM',
  'VISA-CN | BUS | MUL-V365D-DIS | S | KHM',
  'VISA-CN | NBS | DIS-DIS-DIS | S | KHM',
  'VISA-CN | STU (X1) | SIN-V90-NA | S | KHM',
  'VISA-CN | STU (X2) | SIN-DIS-180D | S | KHM',
  'VISA-CN | FAM (Q1) | SIN-V90D-DIS | S | KHM',
  'VISA-CN | FAM (Q2) | SIN-V90D-30D | S | KHM',
  'VISA-CN | FAM (Q2) | DOU-V180D-DIS | S | KHM',
  'VISA-CN | FAM (Q2) | MUL-V365D-DIS | S | KHM',
  'VISA-CN | FAM (S1) | SIN-V90D-NA | S | KHM',
  'VISA-CN | FAM (S2) | SIN-V90D-180D | S | KHM',
  'VISA-CN | FAM (S2) | DOU-V180D-DIS | S | KHM',
  'VISA-CN | FAM (S2) | MUL-V365D-DIS | S | KHM',
  'VISA-HK | TOU | EXPRESS | NA | KHM & FOR',
  'VISA-HK | TOU | DOU-V90D-14D | S | KHM',
  'VISA-AU | TOU (TS) | DIS-DIS-3M | E | KHM',
  'VISA-AU | TOU (FTS) | DIS-DIS-3M | E | KHM',
  'VISA-AU | TOU | BIOMETRIC FEE',
  'VISA-JP | TOU | SIN-V90D-15D | E | KHM',
  'VISA-JP | TOU | SIN-V90D-15D | S | KHM',
  'VISA-JP | TOU | MUL-DIS-15D | S | KHM',
  'VISA-KR | TOU & STV | EXPRESS | NA | KHM & FOR',
  'VISA-KR | STV | SIN-V90D-DIS | E | KHM',
  'VISA-KR | TOU | SIN-V90D-DIS | E | KHM',
  'VISA-US | TOU | SIN-V90D-DIS | S | KHM',
  'VISA-CA | TOU | DIS-DIS-180D | S | KHM',
  'VISA-CA | TOU | BIOMETRIC FEE',
  'VISA-TW | TOU | MUL-V90D-14D | E | KHM',
  'VISA-UK | TOU | DIS - DIS - DIS | E | KHM',
  'VISA-UK | TOU | MUL - V2Y - 6M | E | KHM',
  'VISA-UK | TOU | MUL - V5Y - 6M | E | KHM',
  'VISA-UK | TOU | MUL - V10Y - 6M | E | KHM',
  'VISA-UK | TOU | BIOMETRIC FEE',
  'VISA-EU(FR) | SVS(C) | DIS-DIS-DIS | S | KHM',
  'VISA-EU(CH) | SVS(C) | DIS-DIS-DIS | S | KHM',
  'VISA-EU(DE) | SVS(C) | DIS-DIS-DIS | S | KHM',
  'VISA-EU | TOU | BIOMETRIC FEE',
  'VISA-IN | TOU | DOU-DIS-30D | E | KHM',
  'VISA - RU | TOU | SIN-DIS-DIS | S | KHM',
  'VISA-NZ | TOU | DIS-DIS-DIS | E | KHM',
  'VISA-AE | TOU | SIN-60D-30D | E | KHM',
  'VISA-PK | TOU | SIN-V90D-30D | E | KHM',
 ],
};
